server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rides_service_dev
    username: postgres
    password: sasa
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
