# --- Configuración Específica para Desarrollo ---

logging:
  level:
    com.urbango.whatsappadapter: DEBUG # Log detallado de nuestro código en dev
    # Puedes añadir logging de Feign si necesitas depurar las llamadas
    # feign.client.feign.Logger: DEBUG
