server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notifications_service_dev
    username: postgres
    password: sasa
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

whatsapp:
  apiUrl: "https://api.whatsapp.com/v1/messages"  # Endpoint simulado; revisa la documentación de tu proveedor.
  authToken: "TU_TOKEN_DE_AUTENTICACION"
  senderNumber: "whatsapp:+1234567890"
